name: Map of Pi Merge

# Controls when the workflow will execute
on:
  # Triggers the workflow when build successfully completes
  workflow_run:
    workflows: ["Map of Pi Build"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge:
    name: 🔀 Merge
    runs-on: ubuntu-latest
    # The sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config --global user.name 'map-of-pi[bot]'
          git config --global user.email 'map-of-pi[bot]@users.noreply.github.com'
      
      - name: Debug - Print GitHub Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Head branch: ${{ github.event.workflow_run.head_branch }}"

      - name: Merge dev into main
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev' }}
        run: |
          git checkout main
          git merge dev
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
